### ISSUE TITLE
执行scGNN.py时候，关于cublasSgemm矩阵乘法，我出现了RuntimeError，该怎么解决呢？就是执行最后一段代码

### ISSUE THREAD

**Issue by joyyy111** [juexinwang/scGNN#32]
![1711000756751](https://github.com/juexinwang/scGNN/assets/138951832/aefbf37f-c9a9-4539-a98c-d95a8ac93526)

**Comment by juexinwang** [comment]
You may need to use the specific version of python/numpy/... as recommended

**Comment by wwhgh** [comment]
I also encountered this issue, while the verson of numpy is 1.18.1. 

I followed the scripts in the REPRODUCIBILITY.md and directly used the preproceeed data.
The debug info as follows:


---0:00:00---scRNA starts loading.
---0:00:01---scRNA has been successfully loaded
Mem consumption: 1610100
---0:00:01---Start feature autoencoder training
Mem consumption: 1610356
Traceback (most recent call last):
  File "main_benchmark.py", line 384, in <module>
    recon, original, z = train(epoch, EMFlag=False)
  File "main_benchmark.py", line 291, in train
    recon_batch, z = model(data)
...
...
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

How to fixed that runtime error ? Thanks a lot

**Comment by juexinwang** [comment]
Hi, did you use all the recommended versions of numpy and python?

**Comment by moomight** [comment]
I happened to encounter this situation as well, have you solved this problem? Thanks for your response.

**Comment by moomight** [comment]
> I happened to encounter this situation as well, have you solved this problem? Thanks for your response.

Well, I have solved this issue. Just set torch to use CPU instead of GPU. I write `export CUDA_VISIBLE_DEVICES=""` in terminal, and it works.
